### ISSUE TITLE
Suggestion: Incremental execution

### ISSUE THREAD

**Issue by DrTTrousers** [OHDSI/Strategus#95] opened 2023-10-17 08:48 UTC
Strategus modules execute in the order they appear in the analysis specification. This is great for providing a single framework to run a whole study.

During development however, it would be good if it was possible to "step" through the modules. IE an argument inside execute() that allows for a module to run, complete, and then stop, awaiting user input.

In this way it would be possible to run only parts of an analysis specification, permitting slower systems to run step by step without needing to run the prior steps again.

I will look at adding such a feature, with the repo's blessing.

**Comment by anthonysena** [comment] 2024-07-16 21:35
Providing an update on this issue based on the work happening to refactor the module approach. Modules will be part of the Strategus package and this will make debugging much easier.  Here is how that might look in code:

```r
cdModule <- CohortDiagnosticsModule$new()
debugonce(cdModule$execute)
executionSettings$databaseId = "Eunomia"
cdModule$execute(
  analysisSpecifications = analysisSpecifications,
  executionSettings = executionSettings,
  connectionDetails = connectionDetails
)
```

This is not a fully reproducible example, in part because debugging wouldn't lend itself to that.

**Closed** 2024-08-28 18:21 UTC
Labels: execution
